# Generated by Django 4.1.7 on 2024-03-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=24, verbose_name="用户注册")),
                ("passWord", models.CharField(max_length=24, verbose_name="密码")),
            ],
        ),
    ]
